[package]
name = "keenwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy =              { version = "0.8.1" }

[dev-dependencies]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"

[[bin]]
name = "keenwatch"
path = "main.rs"

